version: '3.7'

volumes:
    postgres:
    pgadmin:

services:
  database:
    container_name: catalog_db
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - catalog_net
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.docker
    # Run a command against the development stage of the image
    depends_on:
      - database
    command: ./startup.sh
    ports:
      - "3333:3333"
    networks:
      - catalog_net
networks:
  catalog_net:
    driver: "bridge"
    
